# Generated by Django 4.2 on 2023-05-27 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user_invited',
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_user',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
    ]
