# Generated by Django 4.2 on 2023-05-28 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_remove_invite_user_invited_invite_invited_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invited_user',
            field=models.EmailField(default=11111, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]