# Generated by Django 4.2 on 2023-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0004_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
